name: PR
on:
  pull_request:

env:
  DOCKER_BUILDKIT: "1"
  K8S_OPENAPI_ENABLED_VERSION: "1.31"

jobs:
  lint:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v3
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: 1.89.0
        components: rustfmt, clippy
    - uses: Swatinem/rust-cache@v2
    - uses: actions-rs/cargo@v1
      with:
        toolchain: 1.89.0
        command: fmt
        args: -- --check
    - uses: actions-rs/cargo@v1
      with:
        toolchain: 1.89.0
        command: clippy
        args: -- --deny warnings
    - uses: actions-rs/cargo@v1
      with:
        toolchain: 1.89.0
        command: install
        args: --locked cargo-deny --version=0.16.2
    - uses: actions-rs/cargo@v1
      with:
        toolchain: 1.89.0
        command: deny
        args: check
  test:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: 1.89.0
    - uses: Swatinem/rust-cache@v2
    - uses: actions-rs/cargo@v1
      with:
        toolchain: 1.89.0
        command: test
